#!/bin/sh
#
#   Copyright 2012 Jonathan M. Reid. See LICENSE.txt
#   Created by: Jon Reid, http://qualitycoding.org/
#   Source: https://github.com/jonreid/XcodeCoverage
#

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${DIR}/envcov.sh

remove_old_report()
{
    pushd ${BUILT_PRODUCTS_DIR}
    if [ -e lcov ]; then
        rm -r lcov
    fi
    popd
}

enter_lcov_dir()
{
    cd ${BUILT_PRODUCTS_DIR}
    mkdir lcov
    cd lcov
}

gather_coverage()
{
    echo "${LCOV}" --gcov-tool ${SRCROOT}/XcodeCoverage/llvm-cov-wrapper --capture -b "${SRCROOT}" -d "${OBJ_DIR}" -o ${LCOV_INFO}
    "${LCOV}" --gcov-tool ${SRCROOT}/XcodeCoverage/llvm-cov-wrapper --capture -b "${SRCROOT}" -d "${OBJ_DIR}" -o ${LCOV_INFO}
}

exclude_data()
{
    "${LCOV}" --gcov-tool ${SRCROOT}/XcodeCoverage/llvm-cov-wrapper --remove ${LCOV_INFO} "/Applications/Xcode.app/*" -d "${OBJ_DIR}" -o ${LCOV_INFO}
    "${LCOV}" --gcov-tool ${SRCROOT}/XcodeCoverage/llvm-cov-wrapper --remove ${LCOV_INFO} "main.m" -d "${OBJ_DIR}" -o ${LCOV_INFO}
    # Remove other patterns here...
}

generate_report()
{
    "${LCOV_PATH}/genhtml" --output-directory . ${LCOV_INFO}
    open index.html
}

find "${OBJ_DIR}" -name SKObjectStoreService.gc* -delete

remove_old_report
enter_lcov_dir
gather_coverage
exclude_data
generate_report
